// List of all vanilla backgrounds that are hireable in towns
::Const.HireableCharacterBackgrounds <- [
	"adventurous_noble_background",
	"anatomist_background",
	"apprentice_background",
	"assassin_southern_background",
	"bastard_background",
	"beast_hunter_background",
	"beggar_background",
	"beggar_southern_background",
	"bowyer_background",
	"brawler_background",
	"butcher_background",
	"butcher_southern_background",
	"caravan_hand_background",
	"caravan_hand_southern_background",
	"cripple_background",
	"cripple_southern_background",
	"cultist_background",
	"daytaler_background",
	"daytaler_southern_background",
	"deserter_background",
	"disowned_noble_background",
	"eunuch_background",
	"eunuch_southern_background",
	"farmhand_background",
	"fisherman_background",
	"fisherman_southern_background",
	"flagellant_background",
	"gambler_background",
	"gambler_southern_background",
	"gladiator_background",
	"gravedigger_background",
	"graverobber_background",
	"hedge_knight_background",
	"historian_background",
	"historian_southern_background",
	"houndmaster_background",
	"hunter_background",
	"juggler_background",
	"juggler_southern_background",
	"killer_on_the_run_background",
	"lumberjack_background",
	"manhunter_background",
	"mason_background",
	"messenger_background",
	"militia_background",
	"miller_background",
	"miner_background",
	"minstrel_background",
	"monk_background",
	"nomad_background",
	"paladin_background",
	"peddler_background",
	"peddler_southern_background",
	"poacher_background",
	"ratcatcher_background",
	"raider_background",
	"refugee_background",
	"retired_soldier_background",
	"sellsword_background",
	"servant_background",
	"servant_southern_background",
	"shepherd_background",
	"shepherd_southern_background",
	"slave_background",
	"slave_southern_background",
	"squire_background",
	"swordmaster_background",
	"tailor_background",
	"tailor_southern_background",
	"thief_background",
	"thief_southern_background",
	"vagabond_background",
	"witchhunter_background",
	"wildman_background"
];

// This code is just for compatibillity with mods which add new backgrounds
::ModularVanilla.QueueBucket.AfterHooks.push(function() {
	// Include the vanilla CharacterBackgrounds array just because it is the most likely place that mods will add their new backgrounds to so we can catch those
	::Const.HireableCharacterBackgrounds.extend(::Const.CharacterBackgrounds);

	// This removes all duplicate CharacterBackgrounds, because all backgrounds in ::Const.CharacterBackgrounds already exist in our array, unless mods add new ones
	::Const.HireableCharacterBackgrounds = ::MSU.Array.uniques(::Const.HireableCharacterBackgrounds);
});
